### ISSUE TITLE
Add WhereSuccess() and WhereFailure().

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#23]

**Comment by RyanMarcotte** [comment]
What is the intent here?  I can guess, but some more information would be helpful for people looking to pick up this task.

**Comment by JohannesMoersch** [comment]
This is for enumerables of results in case for whatever reason you want to discard the other half. I'm open to the idea that discarding the other half of items should be discouraged and this extension shouldn't exist.
