### ISSUE TITLE
Option.Map2(...), Option.Map3(...), etc

### ISSUE THREAD

**Issue by RyanMarcotte** [JohannesMoersch/Functional#27]
Will require some modifications to work with methods defined by `Functional`, but here's the gist of it:
```
public static Option<TResult> Map2<T1, T2, TResult>(Option<T1> option1, Option<T2> option2, Func<T1, T2, TResult> factory)
{
	return option1.HasValue() && option2.HasValue()
		? Some(factory(option1.Value, option2.Value))
		: None<TResult>();
}

public static Option<TResult> Map3<T1, T2, T3, TResult>(Option<T1> option1, Option<T2> option2, Option<T3> option3, Func<T1, T2, T3, TResult> factory)
{
	return option1.HasValue() && option2.HasValue() && option3.HasValue()
		? Some(factory(option1.Value, option2.Value, option3.Value))
		: None<TResult>();
}
```

These methods would be defined on `Option` itself, for usage like so:
`var result = Option.Map2(someOption1, someOption2, (a, b) => ...);`

**Comment by JohannesMoersch** [comment]
You can already accomplish this using the following:
`var result = 
	from a in someOption1
	from b in someOption2
	select a + b`
Added advantage of this approach is that you can join as many as you like.

**Comment by JohannesMoersch** [comment]
The above syntax covers this use case. Closing.
