### ISSUE TITLE
Consider function to invert Option<Result<,>> to Result<Option<>,>

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#29]

**Comment by RyanMarcotte** [comment]
Based on a cursory Internet search, this function appears to typically be named `evert` ("turn inside out"... https://en.wiktionary.org/wiki/evert#English)

**Comment by RyanMarcotte** [comment]
... or `Transpose`

**Comment by JohannesMoersch** [comment]
Transpose seems like the best option
