### ISSUE TITLE
Add PickInto Extension

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#34]
IEnumerable<T> PickInto<T>(this IEnumerable<T> source, out IEnumerable<T> matches, Predicate<T> predicate)

**Comment by RyanMarcotte** [comment]
For my own information, how is that different from `Where`?

**Comment by JohannesMoersch** [comment]
The out parameter is what makes the different. Matches go into the out parameter, and the rest get passed through. It allows the following:
```csharp
public void Method(IEnumerable<T> source)
{
    var leftOvers = source
        .PickInto(out var matchesOne, o => o.ConditionOne())
        .PickInto(out var matchesTwoButNotOne, o => ConditionTwo());

    // Do Something with the three parts of the enumerable.
}
```

**Comment by JohannesMoersch** [comment]
This will be included in the next release.
