### ISSUE TITLE
Option BindToResult (where None becomes Success of Option.None)

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#35]

**Comment by RyanMarcotte** [comment]
Assuming I understand this correctly...?

``` csharp
Option.Some(1337).BindToResult<string>() = Result.Success<Option<int>, string>(Option.Some(1337));
Option.None<int>().BindToResult<string>() = Result.Success<Option<int>, string>(Option.None<int>());
```

**Comment by JohannesMoersch** [comment]
I know I'm countering my own idea, but I'm not convinced an extension that just wraps an option in a success result should exist unless it can at least reduce the need to define success and failure in the generic. There's actually a concept I've been considering exploring of partial results. Basically you can have a PartialSuccess<TSuccess> and a PartialFailure<TFailure> and then Result has implicit type casts from both of these. That way you can just do Result.Success(value) and then if the expect type is a full result with that success type, it works with zero generics.

**Comment by JohannesMoersch** [comment]
Or at least I'm not sure the name I suggested accurate describes what this method does.

**Comment by RyanMarcotte** [comment]
I did read the partial results article that has the implicit casting and it's an interesting idea.  I agree that the use case identified in my previous comment does not come up enough to warrant its own extension method, especially with the clunky syntax.  I'm OK with abandoning that PR.

**Comment by JohannesMoersch** [comment]
I've opened a new issue to talk about the implicit casting: #110

**Comment by RyanMarcotte** [comment]
I've come across a few cases now where the extension method described here would be handy in the middle of method chains, even with the awkward syntax

#122

**Comment by JohannesMoersch** [comment]
Implicit casing has been implemented and helps solve the ask of this issue without introducing methods that don't make much sense otherwise.
