### ISSUE TITLE
Add SelectIfNone, BindIfNone extension methods on Result<Option<T>, TFailure> type

### ISSUE THREAD

**Issue by RyanMarcotte** [JohannesMoersch/Functional#66]
![image](https://user-images.githubusercontent.com/1458084/60305902-73e34c00-98fb-11e9-87a0-5cdcc5eb12a8.png)

**Comment by RyanMarcotte** [comment]
#67

**Comment by JohannesMoersch** [comment]
Vic just found another use case for this extension.

**Comment by RyanMarcotte** [comment]
A pull request has been open for a while that adds these extensions ( #67 )
