### ISSUE TITLE
Add Aggregate/Fold which supports Results natively

### ISSUE THREAD

**Issue by JohannesMoersch** [JohannesMoersch/Functional#70]

**Comment by RyanMarcotte** [comment]
What is the intent here? More information would be helpful for people looking to pick up this task.

**Comment by RyanMarcotte** [comment]
Is it something like this (the `ToSquareTransaction` method)?

``` csharp
public static partial class OrderExtensions
{
    private static readonly Func<Order, SquareMerchantId, Result<Option<SquareTransaction>, SquareTransactionMappingError>>[] _funcCollection =
    {
        (order, merchantId) => order.ToSquareSaleTransaction(merchantId),
        (order, merchantId) => order.ToSquareRefundTransaction(merchantId),
        (order, merchantId) => order.ToSquareInvoicePaymentTransaction(merchantId)
    };

    public static Result<Option<SquareTransaction>, SquareTransactionMappingError> ToSquareTransaction(this Order source, SquareMerchantId merchantId)
    {
        return _funcCollection.Aggregate(
            Result.Failure<Option<SquareTransaction>, SquareTransactionMappingError>(SquareTransactionMappingError.DueToUnknownSquareTransaction(source)),
            (current, func) => current.BindOnFailure(error => error.Match(
                unknown => func.Invoke(unknown.Order, merchantId),
                exception => exception.ToPassthrough())));
    }
}
```

**Comment by JohannesMoersch** [comment]
I really should've written my proposed syntax. I think it was to allow you to collapse a series of results in a custom way.

```csharp
public TResult Aggregate<TSuccess, TFailure, TResult>(this IEnumerable<Result<TSuccess, TFailure>> source, TResult seed, Func<TSuccess, TResult> onSuccess, Func<TFailure, TResult> onFailure);
```

Also maybe a version without seed? However, I think standard aggregate throws an exception on empty collections with a seed, so maybe not?

This extension would allow you take a bunch of results and do whatever the hell you want with them.

**Comment by RyanMarcotte** [comment]
`Aggregate` will not throw an exception for empty collections.  The unmodified seed value is returned in that case.

Is the extension method that you are proposing acting on a collection of already-computed `Result` or a collection of `Result`-producing functions?  If the latter, I think LINQ's `Aggregate` method works just fine because people can specify exactly how `Result`s are aggregated using `Functional` extension methods provided (see the `ToSquareTransaction` method above).

For collections of already-produced `Result`, I think LINQ's `Aggregate` still works fine in that case too.

Maybe it is sufficient to provide documentation and examples on how to aggregate results using the LINQ `Aggregate` method rather than building an extension method?

**Comment by JohannesMoersch** [comment]
When I said standard aggregate up above, I meant the version without the seed. I think that version does throw an exception on empty collections. In any case, I can no longer remember the exact use case for this so maybe it doesn't make sense.

**Comment by RyanMarcotte** [comment]
I somehow missed the [version of `Aggregate` that does not provide a seed](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.aggregate?view=net-5.0#System_Linq_Enumerable_Aggregate__1_System_Collections_Generic_IEnumerable___0__System_Func___0___0___0__).

We may not have a generic use case for our own aggregation extension method, but information on how to potentially perform such an operation using LINQ's `Aggregate` method could still be helpful.  I could do up some "Advanced Scenarios" section in the documentation to give an example of using `Aggregate` to execute a variable number of `Result`-producing functions.  The `README` is getting pretty big too...  What are your thoughts on splitting the documentation up into a set of smaller documents?

**Comment by JohannesMoersch** [comment]
A set of smaller documents would be fantastic. Also, I really need to figure out how to get the GitHub app to send push notifications for comments on issues in this repo...

**Comment by RyanMarcotte** [comment]
Closing, as documentation now exists for how to accomplish `Result`-aggregation functionality using LINQ's `Aggregate` extension method
