### ISSUE TITLE
.NET Standard 2.1+ is not supported by any version of .net framework

### ISSUE THREAD

**Issue by bradrhodes** [JohannesMoersch/Functional#87]
Functional 2.0 targets .net standard 2.1 which won't be supported by .net framework.  Not sure if your intent is to only support .net core or not.

**Comment by JohannesMoersch** [comment]
There are now two versions of Functional.All. There is Function.All, and Functional.All.NetStandard2. The latter maintains compatibility with .NET Standard 2.0 (and .NET Framework). I wanted to add support for the native .NET Standard 2.1 async enumerables which is what prompted the update. For anything on older versions of .NET, they can move to Functional.All.NetStandard2 instead.

I'm currently working out a couple kinks in the beta, but I'm hoping to have a full reason out soon.

**Comment by JohannesMoersch** [comment]
I've accomplished this by forking the 3 async enumerable assemblies into two variants and having each of the All packages reference one or the other.

**Comment by bradrhodes** [comment]
That's reasonable.  Might consider putting up some brief notes on the different nuget packages available on the README.md.
