### ISSUE TITLE
Variants of Result.Try() which only catch a specific exception type

### ISSUE THREAD

**Issue by andrewk-iq** [JohannesMoersch/Functional#88]
It's often useful to be able to catch only a specific type of exceptions (eg: for when a library throws a known exception type which you'd like to catch and handle in a specific way), and let all other exceptions continue to bubble up the stack (because they may be truly exceptional things that your immediate error handling code shouldn't be attempting to handle). However, this doesn't appear to be possible with the current set of `Result.Try()` methods.

**Comment by RyanMarcotte** [comment]
[Polly syntax could be worth mirroring for this](https://github.com/App-vNext/Polly#step-1--specify-the--exceptionsfaults-you-want-the-policy-to-handle)
